server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/multipedidos_a
    username: root
    password: black
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # para pruebas; en prod sería validate
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    default-property-inclusion: non_null

springdoc:
  swagger-ui:
    path: /swagger-ui.html